In [3]:

import cv2
import dlib
import face_recognition

In [4]:
image=cv2.imread("C:\\Users\\anilkrishna\\Downloads\\download (2).jpg")
cv2.imshow("result",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
no_faces=face_recognition.face_locations(image,model="hog")
print(no_faces)

[(22, 269, 58, 233), (42, 113, 78, 77), (30, 73, 66, 37), (42, 173, 78, 137), (42, 221, 78, 185)]


In [6]:
no_faces=face_recognition.face_locations(image,model="cnn")
print(no_faces)

[(29, 76, 69, 37), (17, 272, 57, 233), (37, 116, 77, 77), (37, 224, 77, 185)]


In [7]:
length_of_faces=len(no_faces)
print(length_of_faces)

4


In [8]:
for index,current_face_location in enumerate(no_faces):
    top_pos,right_pos,bottom_pos,left_pos=current_face_location
    current_image=image[top_pos:bottom_pos,left_pos:right_pos]
    cv2.imshow("result",image)
    
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2

# Create a CascadeClassifier Object
face_cascade = cv2.CascadeClassifier("C:\\Users\\anilkrishna\\Downloads\\haarcascade_frontalface_default.xml")

# Reading the image as it is
img = cv2.imread("C:\\Users\\anilkrishna\\Downloads\\download (2).jpg")

# Reading the image as gray scale image
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# Search the co-ordintes of the image
faces = face_cascade.detectMultiScale(gray_img, scaleFactor = 1.05,
                                      minNeighbors=5)
print(type(faces))
print(faces)

for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w,y+h),(0,0,256),3)

resized = cv2.resize(img, (int(img.shape[0]/7),int(img.shape[0]/7)))

cv2.imshow("Gray", img)

cv2.waitKey(0)

cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[232  18  38  38]
 [ 31  27  45  45]
 [ 79  37  36  36]
 [190  42  33  33]
 [140  41  33  33]]
